### ISSUE TITLE
The "leroy-jfp96" test does not work.

### ISSUE THREAD

**Issue by glynawe** [ott-lang/ott#108]
I was particularly interested in trying this one.  If the problem is not in Ott itself, could a correction be made to the test file? 

$ make tests/leroy-jfp96.out
bin/ott   							\
                -o out.thy -o out.v -o outScript.sml 	\
        -o out.tex 						\
                tests/leroy-jfp96.ott                                                      \
&& (latex out; dvips out -o)
Ott version 0.33   distribution of Mon 16 Jan 15:32:01 GMT 2023
File tests/leroy-jfp96.ott on line 96, column 32 - 48:
Warning: Free variables in hom element [[cV]]
File tests/leroy-jfp96.ott on line 138, column 2 - 75:
Error: (in checking and disambiguating quotiented syntax)
meta or sugar production must have a hom for each target - here "isa" is missing

make: *** [Makefile:69: tests/leroy-jfp96.out] Error 2

**Comment by PeterSewell** [comment]
The `%.out` make target builds Isabelle, Coq, HOL4, and LaTeX, but if you
look at tests/leroy-jfp96.ott, you can see that it's only written to
generate HOL4 and LaTeX - there are no homs for those other targets.  If
you try `make tests/leroy-jfp96.hol.out`, that seems to work, at least for
the LaTeX.  I just pushed a tiny fix for the HOL4, but I didn't check
whether the generated HOL4 builds there.

**Comment by palmskog** [comment]
@glynawe note that with the current latest release of Ott ([0.34](https://github.com/ott-lang/ott/archive/refs/tags/0.34.tar.gz)), the Leroy JFP '96 example now builds fine with HOL4 `trindemossen-1`, here are commands starting from the Ott root directory to check:
```shell
$ make world
$ cd hol
$ ../bin/ott ../tests/leroy-jfp96.ott -o leroyScript.sml
$ Holmake
...
leroyTheory (7s)     OK
```
This assumes that HOL4 is installed and `Holmake` is in the PATH.
