### ISSUE TITLE
New to ott and grammars

### ISSUE THREAD

**Issue by Johanvdberg** [ott-lang/ott#17]
Hallo I am new to writing grammars and am looking for a convenient language to define the grammar.

I found ott the prove capabilities look very interesting but first need to learn how to define a grammar:
  - how expression are defined
  - how the types works

Where can I start?

**Comment by PeterSewell** [comment]
On 18 November 2017 at 20:00, Johanvdberg <notifications@github.com> wrote:

> Hallo I am new to writing grammars and am looking for a convenient
> language to define the grammar.
>
> I found ott the prove capabilities look very interesting but first need to
> learn how to define a grammar:
>
>    - how expression are defined
>    - how the types works
>
> Where can I start?
>

The manual?   Or one of the papers?    Or the examples on the web page?
All at:

http://www.cl.cam.ac.uk/~pes20/ott/

best,
Peter

**Comment by palmskog** [comment]
I think the README and web page are clear enough on issue (although more documentation is usually a good thing). Closing.
