### ISSUE TITLE
Trouble Parsing Judgement List Forms

### ISSUE THREAD

**Issue by JoeyEremondi** [ott-lang/ott#20]
I'm just getting started with Ott, translating some of my work over into it, and I'm stuck trying to have list forms representing multiple judgments. Here's a minimal example of the error I'm seeing:

```
metavar typevar, X ::=

indexvar index, i, j, k, n, m ::=

grammar
  T :: 'type_' ::=
  | X :: :: var

  G :: 'eng' ::=
   | empty :: :: env

defns
  Jtype :: '' ::=


  defn
    G |- T <: T' :: :: sub :: sub_ by

    G |- T1 <: T1 .. G |- Tn <: Tn
    ------------------------------- :: example
    G |- T <: T
```

gives the error:
 ` no parses (char 18):     G |- T1 <: T1 ***.. G |- Tn <: Tn`

What I'm doing seems no different to me than what's going on in the Rcd rule of the PoplMark example, which compiles just fine.

Am I missing something? Is there something I have to define to allow list forms in judgment premises? Am I hitting a precedence or ambiguous parse error?

Thanks!

**Comment by mpwassell** [comment]
Hello,

If you want to include list forms with judgements in judgements then you
will need to include the lines:

  formula :: formula_ ::=
   |  judgement                       ::   :: judgement
   |  formula1 .. formulan            ::   :: dots

in your file before the defns section. See Section 12 in the User Guide for
more detail.

Cheers

Mark

**Comment by JoeyEremondi** [comment]
Perfect, I missed that at the beginning of the List section. Thanks!
