### ISSUE TITLE
Function definitions: Ocaml output

### ISSUE THREAD

**Issue by andrewjkennedy** [ott-lang/ott#23]
Does ott support Ocaml output for function definitions? The example in the manual, namely

grammar
  n :: 'n_' ::=
  | 0 :: :: Zero
  | S n :: :: Succ
funs
  Add ::= {{ hol-proof ... }}
fun
  n1 + n2 :: n :: add {{ com a function of type num -> num -> num }}
by
  0 + n2 === n2
  S n1 + n2 === n1 + S n2

Produces the following error with the "-o <file>.ml" option:

warning: internal: prod_of_prodname: searching pn = n_add

Fatal error: exception Not_found

**Comment by francesco-zappa-nardelli** [comment]
Hi Andrew

> Does ott support Ocaml output for function definitions? The example in the manual, namely
> 
> grammar
> n :: 'n_' ::=
> | 0 :: :: Zero
> | S n :: :: Succ
> funs
> Add ::= {{ hol-proof ... }}
> fun
> n1 + n2 :: n :: add {{ com a function of type num -> num -> num }}
> by
> 0 + n2 === n2
> S n1 + n2 === n1 + S n2
> 
> Produces the following error with the "-o .ml" option:
> 
> warning: internal: prod_of_prodname: searching pn = n_add
> 
> Fatal error: exception Not_found

A Not_found exception is always embarrassing, thanks for reporting this.  We were never really happy of the design of the function mechanism, and as a consequence it has not been thoroughly tested: I will investigate this issue.  In meanwhile, if you need to generate OCaml code for a function, we suggest you use an embed section and coding the function explicitly.

Best
	Francesco

**Comment by PeterSewell** [comment]
On 29 January 2018 at 13:52, francesco-zappa-nardelli <
notifications@github.com> wrote:

> Hi Andrew
>
> > Does ott support Ocaml output for function definitions? The example in
> the manual, namely
> >
> > grammar
> > n :: 'n_' ::=
> > | 0 :: :: Zero
> > | S n :: :: Succ
> > funs
> > Add ::= {{ hol-proof ... }}
> > fun
> > n1 + n2 :: n :: add {{ com a function of type num -> num -> num }}
> > by
> > 0 + n2 === n2
> > S n1 + n2 === n1 + S n2
> >
> > Produces the following error with the "-o .ml" option:
> >
> > warning: internal: prod_of_prodname: searching pn = n_add
> >
> > Fatal error: exception Not_found
>
> A Not_found exception is always embarrassing, thanks for reporting this.
> We were never really happy of the design of the function mechanism, and as
> a consequence it has not been thoroughly tested: I will investigate this
> issue. In meanwhile, if you need to generate OCaml code for a function, we
> suggest you use an embed section and coding the function explicitly.
>

IIRC you can use [[ ]] inside such embed sections, which lets you use
object-language syntax.  Not sure hope much that helps - depends on the
scale of the thing
