### ISSUE TITLE
Make context application Fixpoint by default

### ISSUE THREAD

**Issue by JoeyEremondi** [ott-lang/ott#28]
Suppose I've got a set of context rules, which allow for nesting of contexts to build up complex contexts:

```
  CC :: Context_ ::=
    | __ :: :: empty
    | __ << tau1 ,  .. , taun >> :: :: spec %Internal only
    | Obj ( D , __ ) :: :: obj  % Internal only
    | ForAll << X1 , .. , Xn >> . __ :: :: gen
    | \ x . __  :: :: Lambda 
    | __ ( e )                 ::   :: App
    | CC1 [ CC [ __ ] ] :: :: ccApp
```
and context application is defined for `e` as follows:
```
    | CC [ e ] :: M :: ccApp {{coq (appctx_CC_expr [[CC]] [[e]]) }} 
```

As it stands, in generated Coq definitions, the code will not compile. The `ccApp` case requires a recursive call to `appctx_CC_e`, but because its use only occurs in the `hom` for application, Ott doesn't detect the loop and generates using `Definition` instead of `Fixpoint`.

Is it possible to make context application generated using Fixpoint by default, similar to how Substitution currently is? Detecting the recursive reference seems too hard, since it would require parsing hom blocks. 

Or is there some way to "fake" a reference and trick Ott into seeing that the definition is required, maybe with some unused Meta rule?

**Comment by PeterSewell** [comment]
I'd normally define just the atomic contexts, without recursion, and have explicit lists of those if need be - I think easier to work with.   And for that, one doesn't want a Fixpoint.

**Comment by JoeyEremondi** [comment]
Fair enough.
