### ISSUE TITLE
Installing through opam does not install Emacs mode

### ISSUE THREAD

**Issue by Blaisorblade** [ott-lang/ott#29]
The README suggests
> If you have OPAM installed on your system, opam install ott will install the latest Ott version. The Emacs mode will be in `opam config var prefix`/share/ott/emacs, and documentation in `opam config var prefix`/doc/ott.

But after `opam install ott`, `~/.opam/system/share/ott/` is empty, so I need to to check out Ott and copy the Ott mode from inside the repo with with `cp emacs/ott-mode.el ~/.opam/system/share/ott/emacs`

**Comment by hannesm** [comment]
Thanks for the report.  I updated the README to reflect that `ott-mode.el` is now installed to `` `opam config var prefix`/share/emacs/site-lisp `` in  7da83c4.
