### ISSUE TITLE
Evaluation contexts with locally nameless representation

### ISSUE THREAD

**Issue by amaurremi** [ott-lang/ott#47]
The `contextrules` section of ott produces helpful definitions for evaluation contexts. However, this breaks when we choose the locally nameless representation for variables. In that case,`contextrules` does not generate proof assistant functions (specifically the [context applications](https://www.cl.cam.ac.uk/~pes20/ott/top2.html#htoc51) definitions`appctx_E_t`).

For example, running ott on the following code:
```
metavar x ::=
  {{ coq String.string }}
  {{ lex alphanum }}

grammar

t :: '' ::=
  | t1 t2  :: :: app
  | H . t  :: :: ctx {{ coq () }}

H :: '' ::=
  | __ t :: :: appL

contextrules
  H _:: t :: t
```
will produce 
```
...
(** context application *)
Definition appctx_H_t (H5:H) (t_6:t) : t :=
  match H5 with
  | (appL t5) => (app t_6 t5)
end.
```
However, if we declare
```
metavar x ::=
  {{ coq String.string }}
  {{ lex alphanum }}
  {{ repr-locally-nameless }}
```
then such a function will not be produced.

**Comment by PeterSewell** [comment]
On 04/05/2019, Marianna Rapoport <notifications@github.com> wrote:
> The `contextrules` section of ott produces helpful definitions for
> evaluation contexts. However, this breaks when we choose the locally
> nameless representation for variables.

I suspect that was never supported by the locally nameless backend, I'm afraid.
Francesco will know for sure.

best,
Peter

**Comment by francesco-zappa-nardelli** [comment]
Hi Marianna

Peter has been faster than me...

> The contextrules section of ott produces helpful definitions for evaluation contexts. However, this breaks when we choose the locally nameless representation for variables. In that case,contextrules does not generate proof assistant functions (specifically the context applications definitionsappctx_E_t).

I am afraid this is a limitation of the locally-nameless backend: we could not design a general compilation scheme from all of the Ott input language to the locally-nameless representation, in particular for multiple binders and contextrules (more in general for auxfns).

-francesco

**Comment by amaurremi** [comment]
I see, I understand. Thanks for the quick response.
