### ISSUE TITLE
Tex Filtering Seems Broke

### ISSUE THREAD

**Issue by heades** [ott-lang/ott#61]
I've been using OTT for many years now, and I'm quite excited to see some improvements being made.  

I decided to give the latest version a try, but it seems to not be behaving correctly.  

There is a minimal example attached:

[ott-ex.zip](https://github.com/ott-lang/ott/files/3963315/ott-ex.zip)

There you will find an Makefile, OTT spec, and tex file for filtering; I'm running MacOS Mojvae 10.14.6, pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019),and OTT 3.0 (master).

Running the makefile produces the following:

```
ott -i Ex.ott  -o Ex-ott.tex -tex_wrap false -tex_show_meta false -picky_multiple_parses false -tex_filter ex.tex ex-output.tex
Ott version 0.30   distribution of Sun 24 Nov 2019 21:57:16 CET
pdflatex --jobname=ex ex-output.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `ex-output.tex'.
<*> ex-output.tex
                 
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
```
 As we can see the OTT command outputs the following:

```
ott -i Ex.ott  -o Ex-ott.tex -tex_wrap false -tex_show_meta false -picky_multiple_parses false -tex_filter ex.tex ex-output.tex
Ott version 0.30   distribution of Sun 24 Nov 2019 21:57:16 CET
```

No `ex-output.tex` is generated, but `Ex-ott.tex` is generated correctly, but OTT doesn't give us the usual breakdown of the number of clauses and rules.

Reverting back to my previous OTT version 0.25 we don't get any issues:

```
ott -i Ex.ott  -o Ex-ott.tex -tex_wrap false -tex_show_meta false -picky_multiple_parses false -tex_filter ex.tex ex-output.tex
Ott version 0.25   distribution of Thu Sep 4 18:04:34 BST 2014
Definition rules:        1 good    0 bad
Definition rule clauses: 2 good    0 bad
```

The example now builds correctly.

In fact, I tried building about 6 different papers using the new version, but all failed in this same way.  The problem arises only when using `-tex_filtering` I can build tex wrapped specs, but the rule breakdown is never outputted.

**Comment by PeterSewell** [comment]
On Sat, 14 Dec 2019 at 01:52, Harley D. Eades III <notifications@github.com>
wrote:

> I've been using OTT for many years now, and I'm quite excited to see some
> improvements being made.
>
> I decided to give the latest version a try, but it seems to not be
> behaving correctly.
>
This looks like a command-line processing bug I introduced yesterday while
tinkering with the experimental pp generation - should be fixed now.

Peter

**Comment by heades** [comment]
Thanks, Peter!  This fixes the problem. I'm closing this now.
