### ISSUE TITLE
Broken Links to ln_ott and lngen in the Guide

### ISSUE THREAD

**Issue by nxjfxu** [ott-lang/ott#70]
Hi,

These two links in the guide seem to be broken:

http://moscova.inria.fr/%C2%A0zappa/projects/ln_ott/
http://www.cis.upenn.edu/%C2%A0baydemir/papers/lngen/

Apparently the first one is broken by the escaped tilde.  http://moscova.inria.fr/~zappa/projects/ln_ott/ takes me to the correct place.

The second link seems to be down.  Is it supposed to be https://www.cis.upenn.edu/~sweirich/papers/lngen/ ?

**Comment by PeterSewell** [comment]
thanks

**Comment by hannesm** [comment]
fixed in https://github.com/ott-lang/ott/commit/fc08d5c4e1538e4e6bb39fb4289a1c6cc01b88b7, closing this issue.
