### ISSUE TITLE
Release compatible with Coq 8.12

### ISSUE THREAD

**Issue by clarus** [ott-lang/ott#72]
Hello,

Would it be possible to have a new release of `ott` so that it could be compatible with Coq 8.12? Indeed, we have a project https://gitlab.com/nomadic-labs/mi-cho-coq which depends on `ott` for the Coq part, and it seems that the latest version of `ott` (0.31) is not compatible with Coq 8.12.

Thanks!

**Comment by palmskog** [comment]
If @PeterSewell approves I can make a release.

@clarus, in the meantime, you can depend on the `extra-dev` version of the Ott Coq library (`coq-ott.dev`), which supports 8.12 just fine.

**Comment by clarus** [comment]
Thanks, and good idea for our development package.

**Comment by PeterSewell** [comment]
fine by me - many thanks

Peter

**Comment by clarus** [comment]
Hi,

This is to know if there can be a new tag `0.32` to have compatibility with Coq 8.12. As soon as there is a tag I can make a new package for `coq-ott.0.32`.

Thanks!

**Comment by clarus** [comment]
Hello,

A slight ping to know if there can be a release of `coq-ott` compatible with Coq 8.12. I think it can just be the release of the current `master` branch. However, now there is also Coq 8.13 to support.

Thanks.
