### ISSUE TITLE
Defer to coq semantics in step judgement

### ISSUE THREAD

**Issue by elefthei** [ott-lang/ott#75]
Hello, I was wondering how to step from a symbolic premise to its concrete evaluation, by using the underlying proof assistant semantics. The following is the short version of what I am trying to do, hopefully in `step` and not by macro so I can reason about those concrete evaluations in the proof assistant. Is it possible?

```
metavar expvar, x, y, z ::= {{ repr-locally-nameless }}
metavar nat, n ::= {{ coq nat }} {{ coq-equality }} {{ lex numeral }}

grammar

constant, c :: const_ ::= {{ coq-equality }}
 | true  ::  :: true
 | false ::  :: false
 | nat   ::  :: nat

exp, e :: tm_ ::= {{ coq-equality }}
 | x        ::  :: var
 | constant ::  :: constant
 | e1 + e2  ::  :: add

formula :: formula_ ::=
  | judgement      ::  :: judgement
  | [ n1 + n2  ]   ::  :: add_nat {{ coq Nat.plus [[n1]] [[n2]] }}

defns
Jop :: '' ::=

defn
e1 --> e2
::  :: step :: step_ by

% Error
%
% File Foo.ott on line 35 - 36:
% Error: no parses of "n1 + n2 --> [ n1 + n2 ]":
% no parses (char 13): n1 + n2 --> [*** n1 + n2 ]
----------------------- :: add_concrete
n1 + n2 --> [ n1 + n2 ]
```

I expected the formula to work, but I guess it does not because it's in the judgment not the premise.

Here's another attempt at making it work with a similar error

```
metavar expvar, x, y, z ::= {{ repr-locally-nameless }}
metavar nat, n ::= {{ coq nat }} {{ coq-equality }} {{ lex numeral }}

grammar

exp, e :: tm_ ::= {{ coq-equality }}
 | x        ::  :: var
 | con n    ::  :: con
 | e1 + e2  ::  :: add

defns
Jop :: '' ::=

defn
e1 --> e2
::  :: step :: step_ by

% errors
%
% File Foo.ott on line 29 - 30:
% Error: no parses of "con n1 + con n2 --> con {{ coq Nat.plus [[n1]] [[n2]] }}":
% no parses (char 25): con n1 + con n2 --> con {***{ coq Nat.plus [[n1]] [[n2]] }} 
----------------------- :: add_concrete
con n1 + con n2 --> con {{ coq Nat.plus [[n1]] [[n2]] }}
```

**Comment by PeterSewell** [comment]
What you have isn't type-correct: your relation is over a couple of exp's,
but [n1+n2] is a formula (ie a potential premise).

I'm not sure exactly what you're aiming for - perhaps add metaproductions
to your const grammar with coq homs explaining how to evaluate them (but
the coq would have to handle all the non-metaproduction cases, obviously)

Peter

**Comment by elefthei** [comment]
I think the very last line more clear
```
----------------------- :: add_concrete
con n1 + con n2 --> con {{ coq Nat.plus [[n1]] [[n2]] }}
```

And the coq step rule I expect is
```
Inductive step: exp -> exp -> Prop :=
| step_add_concrete: forall n1 n2,
  con n1 + (con n2 --> con (Nat.plus n1 n2).
```

This is definitely a semantic rule not a grammar rule, however I can't seem to make it typecheck.

**Comment by sweirich** [comment]
It looks like you need a grammar for nat, not just a metavar. Then you can add a coq hom for plus. 

```
nat, n :: nat_ ::= {{ coq nat }}
 | 0    ::   :: {{ coq [[0]] }}
 | n1 + n2 ::   :: {{ coq (Nat.plus [[n1]] [[n2]] }} 
```

**Comment by elefthei** [comment]
That worked, thank you!
