### ISSUE TITLE
Latex export: allow `embed`-like functionality that exports before ott commands (instead of after)

### ISSUE THREAD

**Issue by rogerbosman** [ott-lang/ott#79]
I'm trying to flip a mathematical symbol following the `reflectbox` approach [described here](https://tex.stackexchange.com/questions/471324/rotated-vdash-symbol-from-amssymb). For this I need to `usepackage` `graphicx` and declare a `newcommand`, both of which (or at least the `usepackage`) need to be in the preamble. The following example
```
embed {{ tex
\usepackage{graphicx}
\newcommand{\VdashR}{\mathrel{\reflectbox{$\Vdash$} } } }}
...
terminals :: 'terminals_' ::=
  | -||          ::  :: rev_turnstyle_doub {{ tex \VdashR }}
...
```

and then calling
```
ott -i ~/file.ott -o ~/file.tex
latexmk -pdf ~/file
```

does not work, as the embedded tex code gets exported _below_ the other generated code, which use the command. For example, `\newcommand{\ottterminals}` is the first command that uses `VdashR`, but the command is only declared right before `\begin{document}`

Would it be possible to either add some alternative version of `embed` that is inserted before (most of) the preamble, or make this the default behavior for the situation where an `embed` is the first thing encountered in the ott file?

**Comment by rogerbosman** [comment]
Note: given some pointers I would be happy to try to implement this myself, I just wouldn't know where to start

**Comment by PeterSewell** [comment]
if one is using the generated latex in some other document (\include'ing
the Ott output with -tex_wrap false) then one can simply put such commands
before the \include

Peter

**Comment by rogerbosman** [comment]
Thanks, that solves the problem, thanks for your help
