### ISSUE TITLE
how to refer to Coq type in grammar

### ISSUE THREAD

**Issue by bixuanzju** [ott-lang/ott#8]
Maybe a stupid question, say I want to model a simple calculus where literals are modeled by Coq `nat` type. The grammar is as follows:

```
e ::= i | e e | ...
```
where `i` stands for literals.

In Coq, I would write

```
Inductive trm : Set :=
| trm_lit   : nat -> trm
| trm_app   : trm -> trm -> trm
...
```
My question is how to write it in ott format
```
e :: 'trm_'     ::= {{ com expressions }}
  | i             ::   :: lit {{ com literals }}
  | e1 e2          ::   :: app {{ com applications }}
...
```
This is clearly not right, I don't know how to refer to Coq `nat` in the clause `i`. Even If this is somehow possible, another question is how to quantify over natural numbers in inductive definition, for example
```
----------------
E |- i : nat
``` 
The corresponding Coq definition should quantify over natural numbers, something like
```
Inductive typing : tenv -> trm -> typ -> Prop :=
| typing_lit : forall E n,
    ok E ->
    E |= (trm_lit n) ~: typ_int
...
```
Any pointers would be appreciated!

**Comment by PeterSewell** [comment]
Add a metavar declaration for i with a Coq type hom mapping it to the Coq
nat, as:

http://www.cl.cam.ac.uk/~pes20/ott/ott_manual_0.25.html#htoc14

If you want to parse concrete terms, you'll also want to specify how they
should be lexed there.

Or, if you also want some syntax for nat expressions, you can define
another grammar rule for i, with a Coq type hom and a {{ phantom }} hom, to
suppress generation of the corresponding inductive type definition.

Peter

**Comment by bixuanzju** [comment]
Thanks!
