### ISSUE TITLE
X flag does not suppress LaTeX output

### ISSUE THREAD

**Issue by katshun0307** [ott-lang/ott#83]
The documentation says on section 3 about flags,
>  One can also use an X flag here to suppress a production in the generated LaTeX.

When I write  
```
 | ( t )     :: X :: paren
```
and compile (`ott -o system.tex system.ott -tex_show_meta false && pdflatex system.tex`),
`(t)` still appears as syntax on generated pdf.

However, if I put the `M` flag, the production is suppressed. Is this a typo in the docs or am I missing something?

**Comment by PeterSewell** [comment]
I think that line in the documentation is just out of date (I pushed a
fix). There's a command-line option:

-tex_suppress_category <[]>        Suppress productions and rules with
this category in TeX output

Peter

**Comment by katshun0307** [comment]
Thanks! 
`-tex_suppress_category` worked for me.
